<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Login.aspx.cs" Inherits="AnalisisMedicoDetalle.Login" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
       <div class="container">
        <div class="panel-primary">
            <div class="panel-heading">
             <p class="text-white bg-gradient-primary">Registro de Usuarios</p>
            </div>
             
            <div class="panel-body">
                <div class="form-horizontal col-md-12" role="form">
                    <div class="form-group label-floating">
										
                                            <div class="form-group label-floating">
											  <asp:Label ID="Label2" runat="server" class="control-label" Text="Nombres"></asp:Label>
											   <asp:TextBox ID="NombresTextBox" runat="server" class="form-control" MaxLength = " 200 " ></asp:TextBox>
											</div>

                                            <div class="form-group label-floating">
											  <asp:Label ID="Label5" runat="server" class="control-label" Text="Clave"></asp:Label>
											   <asp:TextBox ID="ClaveTextBox" runat="server" class="form-control" Type="password"  ></asp:TextBox>
											</div>
 
                </div>
            </div>

            <div class="panel-footer">
                <div class="text-center">
                    <div class="form-group" style="display: inline-block">
                        <asp:Button ID="Acceder" CssClass="col-md-4 col-sm-4 btn btn-success" runat="server" Text="Acceder" Height="2.5em" Width="10em" OnClick="AccederButton_Click"/>
                    </div>
                </div>
            </div>
        </div>
    </div>

               <div class="col-sm-2">
                        <asp:LinkButton runat="server" ID="AgregarGrid" ValidationGroup="Analisis" CssClass="btn btn-outline-info btn-md" Text="Agregar" OnClick="AgregarGrid_Click"></asp:LinkButton>
</div>

             <%--GRID--%>
                <asp:GridView ID="Grid" CssClass=" col-md-offset-4 col-sm-offset-4" runat="server" DataKeyNames="DetalleAnalsisId" AllowPaging="true" PageSize="10" ShowHeaderWhenEmpty="false" AutoGenerateDeleteButton="true" CellPadding="4" ForeColor="#333333" GridLines="None" Width="767px" AutoGenerateColumns="false" OnRowDeleting="Grid_RowDeleting" OnPageIndexChanging="Grid_PageIndexChanging">                         
                    <Columns>
                        <asp:BoundField DataField="DetalleAnalsisId" HeaderText="Tipo de Analisis" /><asp:BoundField />
                         <asp:BoundField DataField="Analsis" HeaderText="Analisis" /><asp:BoundField />       
                        <asp:BoundField DataField="Resultado" HeaderText="Resultado" /><asp:BoundField />
                    </Columns>     
                    <EmptyDataTemplate><div style="text-align:center">No hay datos en el Grid.</div></EmptyDataTemplate>
                         <AlternatingRowStyle BackColor="White" />

                            <EditRowStyle BackColor="#2461BF" />
                            <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                            <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                            <RowStyle BackColor="#EFF3FB" />
                            <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                            <SortedAscendingCellStyle BackColor="#F5F7FB" />
                            <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                            <SortedDescendingCellStyle BackColor="#E9EBEF" />
                            <SortedDescendingHeaderStyle BackColor="#4870BE" />
                </asp:GridView>




    </form>
</body>
</html>
